version: '3.7'

services:

  api:
    build: server\Spoint
    depends_on:
      - mongo
    ports:
    - 5002:80
    networks:
      - spoint
    environment:
      - "mongoConnection__server=mongodb://mongo:27017/spoint"

  mongo:
    image: mongo:latest
    ports:
    - 27018:27017
    networks:
      - spoint

networks:
  spoint: